OWASP/threat-dragon

README.md, index.html
Links to the github code migrated to owasp area.
Still to do are the links to the releases area, which should be done for next release, and the code analysis
=> migrate some links to owasp area

README.md, package.json, td/public/app/layout/topnav.html, td/views/login.pug
**- Summary**
Update to new docs page
**- Tests**
NA
**- Description for the changelog**
Update docs link
**- Any other info**
=> Update docs link

setup-env.md, td/config/passport.config.js
**Summary**
Allow to configure github scope by setting `GITHUB_SCOPE` env var - to support private repos, not only public ones.
fix #8 - allow to configure GITHUB token scope
**Other info**
=> feat: make github scope configurable

README.md
**Summary**
Adding a section about running using docker to the README
Closes: #71
Using the `.env` configuration does not work with the `--env-file` flag when running the docker container.  Mounting the `.env` file works as expected.  This PR adds a note to the README to address this. 
**Other info**
N/A
=> Update README for Docker usage

.gitmodules, README.md, dev-notes.md, setup-env.md
**Summary**
Bring docs and dev notes into one place, this Threat Dragon repo.
* The file `dev-notes.md` has been brought over from the threat-dragon-core repo and some changes made to bring it up to date, mainly dotenv notes
* `README.md` and `setup-env.md` updated
* docs directory is the github.com/threatdragon/threatdragon.github.io repo referenced as a github submodule
Bring docs and dev notes into threat dragon repo
**Other info**
This satisfies issue #80 .
Note that docs is a github submodule because we do not want it to be a dependency via npmjs. Using a submodule means that the docs are easily accessed from the source code ... in the hope that they will be more likely to be kept up to date
=> Bring docs and dev notes into one place

.github/workflows/docker-build.yaml
**Summary**
Adds a build action to build a docker container
Adding GitHub action to build the docker image using a cache
Closes #104 
**Other info**
This work is based on https://docs.docker.com/ci-cd/github-actions/
When we are ready to start pushing official images, we can do this in an automated way.  We will need to add dockerhub credentials as secrets to the repository, then add the following step to the action:
```
- name: Login to Docker Hub
uses: docker/login-action@v1
with:
username: ${{ secrets.DOCKER_HUB_USERNAME }}
password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
```
To enable the push, update the build step to have `push: true`.  Also ensure that the tags are correct.
=> Adding build action for docker container

td.server/.eslintrc.js, td.server/src/helpers/encryption.helper.js, td.server/test/app_spec.js, td.server/test/config/loggers.config_spec.js, td.server/test/config/passport.config_spec.js, td.server/test/config/routes.config_spec.js, td.server/test/config/securityheaders.config_spec.js, td.server/test/config/session.config_spec.js, td.server/test/controllers/error_spec.js, td.server/test/controllers/githublogincontroller_spec.js, td.server/test/controllers/homecontroller_spec.js, td.server/test/controllers/threatmodelcontroller_spec.js, td.server/test/express.mocks.js, td.server/test/test-setup.spec.js
**Summary**
Uses reusable express mocks for `td.server` tests
Chore: Cleanup tests by using reusable mocks for unit testing of td.server (Closes #111 )
**Other info**
Just some testing cleanup, no *functional* changes to application code (I did update eslint rules to enforce no-var, and found one instance that was missed by previous refactors)
=> Test cleanup

td.vue/TODO, td.vue/src/store/modules/branch.js, td.vue/src/store/modules/provider.js, td.vue/src/store/modules/repository.js, td.vue/src/store/modules/threatmodel.js, td.vue/tests/unit/store/modules/branch.spec.js, td.vue/tests/unit/store/modules/provider.spec.js, td.vue/tests/unit/store/modules/repository.spec.js, td.vue/tests/unit/store/modules/threatmodel.spec.js
**Summary**
The state previously was not cleared on fetch actions causing an incorrect state should the fetch action fail, leading to 500 errors.  Mostly notable when switching between local and remote IDPs.
State is now cleared on fetch actions
**Other info**
V2 only, Vue specific
=> State is cleared on fetch actions

td.site/src/app/core/diagrams/diagrameditor.html, td.site/src/app/core/templates.js
**Summary**
Issue #60 asks that the button to return from the diagram editor is made more obvious
The image has been changed to arrow-left, and moved to be on the far right. The delete and reload buttons have been moved to far left so that they are disassociated from the save and return
make return for diagram editor more obvious
**Other info**
=> make return for diagram editor more obvious (issue #60)

td.site/src/app/core/services/joint.shapes.tm.js
**Summary**
boundaries are now black, so that the only colour is for components with unmitigated threats
remove colour to make boundaries black
**Other info**
looks a lot better, and is better for red/green colour sightedness
=> make boundaries black, removing colour

td.vue/src/service/x6/graph/data-changed.js, td.vue/src/service/x6/shapes/trust-boundary-box.js, td.vue/src/service/x6/shapes/trust-boundary-curve.js, td.vue/tests/unit/service/x6/graph/data-changed.spec.js, td.vue/tests/unit/service/x6/shapes/trust-boundary-curve.spec.js
**Summary**
Removes the green color from trust boundaries, defaults to black.
Trust boundaries are black as seen in #150
=> Removing the green color from trust boundaries per #150

td.site/package-lock.json, td.site/package.json, td.site/src/app/core/templates.js, td.site/src/app/core/threatmodels/threatmodelreport.html
**Summary**
It seemed odd to have the  'cross' icon for when we return from an action. This was changed for the diagram view to a left arrow, and this pull request changes the 'Return' button on the report view to have a left-arrow as well
return icon now left arrow not cross
**Other info**
=> return icon now left arrow not cross

td.desktop/app/layout/shell.js, td.desktop/installer-win.js, td.desktop/test/spec/layout/shell_spec.js
**Summary**
Replaced the old repo link with the new repo link
It replaces the old GitHub repo link with the new GitHub repo link.
It does not replace GitHub links when they get broken by replacing.
**Other info**
Describe the bug
https://github.com/OWASP/threat-dragon-desktop is still used.
Expected behaviour
Users should visit https://github.com/OWASP/threat-dragon
To Reproduce
Go to "Help" in Main menu and click "Check for update", and it takes users to the old repo.
=> replaced the old repo link with the new repo link

td.vue/tests/e2e/smokes/home.js, td.vue/tests/e2e/specs/home.js, td.vue/tests/e2e/specs/logout.js
**Summary**
It seems as though browserstack/cypress is failing on some syntax.  This is just a test to see if it will pass the e2e smoke test automation.
=> Updating e2e tests

README.md
This commit removes the `git init` step, which is unnecessary and potentially
dangerous if done in, e.g., a user's Documents directory.
It also updates the documentation to tell the user where the clone will go.
(It also fixes a typo in the description of the web application.)
**Summary**
This updates the installation instructions so that users don't end up
running `git init` somewhere they don't want to.  If they did so, it
turns the current directory into a git repository.
Remove unnecessary `git init` step from Installing section
=> Remove unnecessary `git init` step from Installing section

td.vue/src/components/Graph.vue, td.vue/src/plugins/fontawesome-vue.js, td.vue/src/styles/bootstrap.scss, td.vue/src/views/Diagram.vue
**Summary**
Moving the temporary keyboard shortcuts listing on the graph page to a more production-ready location
Added a button on the graph ui to open a modal showing all shortcuts
**Other info**
Because the shortcuts include things you can do with the mouse, I intentionally named it "shortcuts" as opposed to keyboard shortcuts.  I think using the word "actions" may be confusing, because a user might think that an action has to do with the threat model.
The proposed implementation:
Button:
Modal:
=> V2/diagram UI

td.desktop/core/services/threatengine.js, td.desktop/test/core/services/threatengine_spec.js
**Summary**
Fix for the context threat  generation in issue #264 
Ensures that the threat is suggested for unencrypted public data flows
fix context threat  generation 
**Other info**
=> Closes #264 Context Threat Generation does not work

td.desktop/package.json
**Summary**
The threat model files were not being copied across for td.desktop when invoking `npm run build:models` under Windows
sort out globstars for cross-platform
**Other info**
The fix has to be cross platform, and had to be written out explicitly (no **) so that it would work for both MacOS and Windows. Linux is well-behaved with either way of doing it, of course
=> bugfix: sort out globstars for cross-platform, fixes #267

td.desktop/app/layout/shell.js, td.desktop/test/layout/shell_spec.js
**Summary**
Best I could do to update menu items, only managed to move developer tools menu item to less used dropdown
Closes #266 
move developer tools menu item to less used dropdown
**Other info**
=> Close  #266 move developer tools menu item to less used dropdown

td.site/package-lock.json, td.site/package.json, td.site/webpack.config.js
**Summary**
json-rules-engine package was not updated for td.site. Updating and removing unused curriable from webpack
Closes bug #279 
update td.site json-rules-engine package
**Other info**
Note that the td.site testing had to be disabled. The app works on all my browsers, but the tests have a weird error on tests : 
```
24 09 2021 09:45:30.467:ERROR [framework.browserify]: bundle error
24 09 2021 09:45:30.470:ERROR [framework.browserify]: SyntaxError: 'import' and 'export' may appear only with
'sourceType: module' (1056:0) while parsing /Users/jon.gadsden/owasp/bugfix-threatengine-error/td.site/node_modules/jsonpath-plus/dist/index-browser-esm.js
while parsing file: /Users/jon.gadsden/owasp/bugfix-threatengine-error/td.site/node_modules/jsonpath-plus/di …
```
=> Closes #279 update td.site json-rules-engine package

.github/workflows/.zap-rules-web.tsv, td.vue/TODO, td.vue/src/components/Graph.vue, td.vue/src/i18n/en.js, td.vue/src/router/index.js, td.vue/src/service/demo/demo-threat-model.js, td.vue/src/service/demo/index.js, td.vue/src/service/demo/legacy-desktop-model.js, td.vue/src/service/demo/legacy-model-2.js, td.vue/src/service/demo/legacy-model.js, td.vue/src/service/provider/github.provider.js, td.vue/src/service/provider/local.provider.js, td.vue/src/store/modules/threatmodel.js, td.vue/src/views/ThreatModel.vue, td.vue/src/views/demo/SelectDemoModel.vue, td.vue/tests/e2e/specs/demo.js, td.vue/tests/unit/router/index.spec.js, td.vue/tests/unit/service/provider/github.provider.spec.js, td.vue/tests/unit/service/provider/local.provider.spec.js, td.vue/tests/unit/store/actions/locale.spec.js, td.vue/tests/unit/store/modules/locale.spec.js, td.vue/tests/unit/store/modules/threatmodel.spec.js, td.vue/tests/unit/views/demo/selectDemoModel.spec.js
**Summary**
Adding the ability to interact with a handful of the demo threat models.
Demo Threat Models are now hooked up and can be edited using v2 (with local/guest or github auth)
**Other info**
These are not actually downloaded from anywhere: they are included in the front-end package to avoid unnecessary network chatter.
=> v2/Demo Threat Models

td.site/karma.conf.js, td.site/package.json
**Summary**
Enables td.site tests
Re-enabling td.site tests.  For td.site, please only use `npm run test` moving forward, or you may not be testing the most up-to-date code
**Other info**
Discussion on implementation in #281
=> Enable td.site Tests 

README.md
Have dockerhub example use the "stable" version as suggested
**Summary**
**Other info**
=> Update README.md dockerhub example to match recommendation

td.vue/TODO, td.vue/package-lock.json, td.vue/package.json
**Summary**
Updates Bootstrap dev dependency in td.vue to 4.6.1
The sass compiler was [warning about division](https://sass-lang.com/documentation/breaking-changes/slash-div) when building td.vue.  This was from the Bootstrap dependency and was fixed in version 4.6.1
=> Updating bootstrap to 4.6.1

td.vue/TODO, td.vue/src/service/x6/graph/events.js, td.vue/tests/unit/service/x6/graph/events.spec.js
**Summary**
The graph UI now reflects changes to the data (such as "out of scope".
This is technically done when a cell is unselected.  
**Other info**
@jgadsden - FYI, I know you're planning to dig in soon.  Here's my thoughts on the current behavior for data changing in the graph:
The state is only updated when a cell is un-selected. This could or even should change to be a proper data binding in the future.  For now, it's an intentional design decision that follows how other metadata is updated (such as the names of properties).  This is not to say it's a *good* decision, we may want to revisit this before anything is released.  It doesn't feel super intuitive to have to un-select a cell to see data changing.
From a UX perspective, I think it'd make …
=> Graph UI updates when data changes

td.vue/src/views/Report.vue, td.vue/tests/unit/views/report.spec.js
**Summary**
Removes the "Print PDF" button from the Desktop version
Printing to a PDF is a standard OS feature.  There is no current need for a separate button to print to PDF.
Closes #342 
**Other info**
Tested that Ubuntu, MacOS and Windows all have native "print to pdf" features from the system print dialogue.  This appears to work as expected from the electron wrapper.
=> Removing "print PDF" button from desktop version

td.vue/src/components/KeyboardShortcuts.vue, td.vue/src/service/x6/graph/graph.js, td.vue/tests/unit/service/x6/graph/graph.spec.js
**Summary**
it is difficult to select a process diagram element and it can not be deleted using the 'red cross'. Once selected the trashcan icon can be used or the delete key
rubberbanding is useful for selecting multiple components and also deleting them. This allows easier selection of diagram elements
**Other info**
panning was initially interfering with rubberbanding, but we now have both
=> add rubberbanding alongside panning

.gitignore, docs/development/testing/e2e.md, td.vue/package.json, td.vue/pnpm-lock.yaml, td.vue/tests/e2e/specs/demo.js, td.vue/tests/e2e/specs/logout.js, td.vue/tests/e2e/specs/threatmodel/report.js, td.vue/tests/e2e/support/index.js
**Summary**
end to end tests are failing when run by BrowserStack. This is because BrowserDStack uses a later version of cypress than the present version of vue-cli-service
update e2e test specs for latest cypress syntax, update vue-cli-service to use the latest version of cypress
**Other info**
this is not really worth reviewing - creating the pull request because it is on a branch
=> update e2e test specs for latest cypress syntax

td.server/src/helpers/logger.helper.js
**Summary**
Just noticed the typo in the logs while running the service
threat-drgaon => threat-dragon in logger service name settings
**Other info**
Note that the same typo exists in `main` and `v2-development` branches
=> Fix typo in logger service name settings

.github/workflows/browserstack.yaml, .github/workflows/ci.yaml, .github/workflows/deploy.yaml
**Summary**
There is [a known bug in npm](https://github.com/nodejs/node/issues/42397) versions 16.14.1 and 16.14.2. The github workflows were fixed at node version 16.14.0 until a fix was in place. Node 18.2.0 is now released and stable, so moving to that version instead
move to node 18 for github workflows
**Other info**
This reverts the change that temporarily fixed the node version to 16.14.0 in commit 82c9d49d2d3a315650a7aed7e1b3a3308a7b44a7
=> move to node 18 for github workflows

docs/README.md, td.server/src/app.js
**Summary**
Rate limiting is stopping some automated end-to-end tests to fail
Provide rate limiting only when running in production environments
rate limiting only for production environments
**Other info**
=> Rate limiting only for production environments

td.vue/src/components/printed-report/ExecutiveSummary.vue, td.vue/src/components/printed-report/ReportEntity.vue, td.vue/src/components/report/ReportEntity.vue
**Summary**
This fixes some multi line display issues like as follows:
1. When you review the report, `mitigations` inside of table don't support multi-line.
2. When you print the analyzed report out , `High level system description` and table under the diagram don't support it.
It's related with https://github.com/OWASP/threat-dragon/issues/468
I added CSS for the issue to fix.
**Other info**
=> Fix some multi line issues

td.server/src/app.js
**Summary**
This reapplies the rate limiting if process.env.NODE_ENV 'development' is used, so rate limiting is only disabled if process.env.NODE_ENV === 'test'
no rate-limiting for test environments
**Other info**
=> no rate-limiting for test environments

td.server/src/config/routes.config.js, td.server/src/controllers/auth.js, td.server/src/controllers/homecontroller.js, td.server/test/controllers/homecontroller.spec.js
**Summary**
Allow logout for unauthenticated / expired sessions
allow logout without authorisation
**Other info**
POST, PUT and DELETE will always require authentication
logout using GET will now succeed
=> always allow logout using GET

td.server/src/controllers/homecontroller.js, td.server/test/controllers/homecontroller.spec.js
**Summary**
reverts breaking change to homecontroller
revert breaking change to homecontroller
**Other info**
Reverts change to the homecontroller, which I did in an earlier pull-request #480 because I misunderstood one of the routes
=> revert breaking change to homecontroller

td.server/test/controllers/threatmodelcontroller.spec.js, td.vue/src/service/demo/v2-threat-model.js, td.vue/src/service/migration/diagram.js, td.vue/src/store/modules/threatmodel.js, td.vue/src/views/NewThreatModel.vue, td.vue/tests/e2e/specs/data/demo.js, td.vue/tests/unit/service/migration/diagram.spec.js, td.vue/tests/unit/store/modules/threatmodel.spec.js
**Summary**
With one eye looking towards the [Open Threat Model](https://github.com/iriusrisk/OpenThreatModel) ,  the version is changed to tdVersion in the Threat Dragon schema
schema uses tdVersion
**Other info**
=> schema uses tdVersion

td.vue/src/components/Graph.vue, td.vue/src/components/ThreatEditModal.vue, td.vue/src/service/threats/index.js, td.vue/tests/unit/components/graph.spec.js, td.vue/tests/unit/components/threatEditModal.spec.js
**Summary**
It would be good to have a 'Cancel' button for new threats, so that it is a one click delete rather than the confirm dialog box for the normal 'Delete'
Add a new button 'Cancel' if it is a new threat, not an existing threat
**Other info**
=> add cancel button for new threat

td.server/test/controllers/threatmodelcontroller.spec.js, td.vue/src/service/demo/v2-threat-model.js, td.vue/src/service/migration/diagram.js, td.vue/src/store/modules/threatmodel.js, td.vue/src/views/NewThreatModel.vue, td.vue/tests/e2e/specs/data/demo.js, td.vue/tests/unit/service/migration/diagram.spec.js, td.vue/tests/unit/store/modules/threatmodel.spec.js
**Summary**
The change to 'tdVersion' from 'version' breaks stuff - so revert it back to 'version'
revert name change for threat model version
**Other info**
=> revert name change for threat model version

td.vue/src/components/GraphMeta.vue, td.vue/src/components/GraphProperties.vue
**Summary**
Disables 'New Threat' button if diagram component is out of scope, and disables Reason text box if in scope
disable new threat button and enable reason text if out of scope
**Other info**
=> disable new threat button and enable reason text if out of scope

td.vue/src/service/entity/default-properties.js, td.vue/src/service/x6/graph/events.js, td.vue/tests/unit/entity/default-properties.spec.js
**Summary**
This provides a default label for Data Flows and ensures that Trust Boundary Boxes are in the background
Trust Boundary box to background and default Data Flow label
**Other info**
=> Trust Boundary box to background and default Data Flow label

td.vue/src/components/GraphButtons.vue, td.vue/src/i18n/en.js
**Summary**
Move the delete button away from the commonly used buttons, rely on redo/undo instead of a delete confirmation modal
move delete button away from commonly used ones
**Other info**
=> move delete button away from commonly used ones

td.vue/src/components/Graph.vue, td.vue/src/store/modules/threatmodel.js, td.vue/src/views/ImportModel.vue, td.vue/src/views/MainDashboard.vue, td.vue/src/views/NewThreatModel.vue, td.vue/src/views/OauthReturn.vue, td.vue/src/views/ThreatModel.vue, td.vue/src/views/ThreatModelEdit.vue, td.vue/src/views/UpgradeDiagram.vue, td.vue/src/views/git/BranchAccess.vue, td.vue/src/views/git/RepositoryAccess.vue, td.vue/src/views/git/ThreatModelSelect.vue
**Summary**
When using the desktop it is desirable that models are saved without a dialog box being shown - unless it is SaveAs. the browser security model stops this, so the desktop saves will have to be done in the backend electron server.
preparation for desktop save of models
**Other info**
=> preparation for desktop save of models

docs/development/api.md, docs/development/testing/adhoc.md, docs/development/testing/unit.md, td.server/src/config/routes.config.js, td.server/src/controllers/threatmodelcontroller.js, td.server/test/config/routes.config.spec.js, td.vue/src/main.desktop.js, td.vue/src/service/api/threatmodelApi.js, td.vue/tests/unit/service/api/threatmodelApi.spec.js
**Summary**
This add a new server API that provides the organisation details off the provider.
This will help to unblock pull-request #546 
Add server API for provider organisation details
**Other info**
Closes #568
=> Add server API for provider details

README.md, docs/development/actions/codeql.md, docs/home/trust/sast.md
**Summary**
removes remaining references to LGTM, and adds the CodeQL badge to the project read-me file
Closes #557 
remove LGTM and add CodeQL badge
**Other info**
Note that CodeQL has been running on Threat Dragon for some time now - reporting Highs and Criticals but not Mediums and Lows
=> remove LGTM and add CodeQL badge

td.server/package.json, td.server/pnpm-lock.yaml
**Summary**
Trivy is reporting various CVEs against jsonwebtoken versions <= 8.5.1
update jsonwebtoken to latest
**Other info**
CVEs:
* CVE-2022-23529 
* CVE-2022-23539 
* CVE-2022-23540
* CVE-2022-23541
=> update jsonwebtoken to latest

.github/workflows/ci.yaml, .github/workflows/release.yaml, README.md, docs/development/actions/ci.md, package.json, td.server/package.json, td.vue/package.json
**Summary**
Removes references to codecov, as this has been stubbed out
No longer using codecov and unlikely to use it in the future
remove references to codecov
**Other info**
Closes #446
=> remove stubbed out codecov

ThreatDragonModels/v2-new-model.json, ThreatDragonModels/v2-threat-model.json, docs/development/example-store.json, docs/development/schema/owasp.threat-dragon.schema.json, td.vue/package.json, td.vue/src/components/Graph.vue, td.vue/src/components/ThreatEditDialog.vue, td.vue/src/service/demo/v2-new-model.js, td.vue/src/service/demo/v2-threat-model.js, td.vue/src/store/modules/threatmodel.js, td.vue/src/views/NewThreatModel.vue, td.vue/src/views/ThreatModel.vue, td.vue/src/views/ThreatModelEdit.vue, td.vue/src/views/git/ThreatModelSelect.vue, td.vue/tests/e2e/fixtures/v2-model.json, td.vue/tests/e2e/fixtures/v2-new-model.json, td.vue/tests/unit/components/graph.spec.js, td.vue/tests/unit/components/threatEditModal.spec.js
**Summary**
Multiple diagrams are not (yet) supported by version 2.x.  Any save of diagrams is folded into the first diagram
This pull request adds diagram.id to version 2.x, in the same way as the existing version 1.x, and provides for the diagram ID to be unique for the lifetime of the model
support multiple diagrams
**Other info**
Closes #582 "First diagram overwritten when creating multiple diagrams" and  also closes #583 "Reinstate diagram IDs"
=> support multiple diagrams

README.md, docs/development/environment.md, docs/development/local.md, docs/development/testing/adhoc.md, docs/home/about/about.md, docs/home/trust/incidents.md, docs/usage/install/docker.md, docs/usage/install/web.md, td.server/src/env/ThreatDragon.js, td.server/src/helpers/encryption.helper.js, td.server/src/providers/index.js
**Summary**
The renaming of docs/development/environment.md was not implemented correctly, resulting in many broken links
fix up for renaming of docs environment page
**Other info**
closes #587
=> fix up for renaming of docs environment page

td.vue/src/desktop/desktop.js, td.vue/src/desktop/menu.js, td.vue/tests/unit/desktop/menu.spec.js, td.vue/tests/unit/views/homePage.spec.js
**Summary**
The recent document list of recently accessed threat models was ignored - it could be selected but the models were not opened
implement opening of recent threat model files
**Other info**
Closes #590
=> implement opening of recent threat model files

docs/development/local.md, docs/home/about/credits.md, docs/usage/collaboration/linking.md
**Summary**
In some parts of the docs Threat Dragon is not cased as a proper noun.
Ensure usage of "Threat Dragon" is as a proper noun in docs
**Other info**
Note: There is one more occurrence in `threat-dragon/docs/development/cli.md` however I can't find in the current v2 branch the CLI setup. Unsure if described functionality still exists. If it does please point me to the right location.  
https://github.com/OWASP/threat-dragon/blob/6893bcb89beca16e0d2a070765a2abd507a0fea7/docs/development/cli.md?plain=1#L58
=> [T/t]hreat dragon -> Threat Dragon

README.md, docs/home/trust/dast.md
**Summary**
Like the [www repo](https://github.com/OWASP/www-project-threat-dragon/pull/33) changes v2 to be released in 2023. 
Also fixes a mistake with DAST and SAST 
Minor readme and doc changes
=> Minor cleanup of doc

td.vue/src/components/report/Coversheet.vue, td.vue/src/views/ReportModel.vue
**Summary**
Swaps usage of `fixed` to `sticky` so that content is pushed down by correct space and not hidden by the report options.  
Resolves layout issues at the top of web report. Closes #598, closes #597 
**Other info**
I'm unsure what the projects minimum browser support is. Please check and confirm if support is satisfactory https://caniuse.com/css-sticky
=> Report layout fixes

td.vue/src/components/DashboardAction.vue, td.vue/src/views/MainDashboard.vue
**Summary**
By applying height 100% we can get actions to have equal height. Remaining changes move the `2rem` from margin and places it as outer padding.
Dashboard actions kept to equal height. Closes #603
=> Dashboard actions kept to equal height

td.vue/src/i18n/de.js, td.vue/src/i18n/en.js, td.vue/src/i18n/ru.js, td.vue/src/i18n/uk.js, td.vue/src/views/HomePage.vue, td.vue/tests/e2e/specs/home.cy.js
**Summary**
This pull-request provides margins around the cupcake image to stop the text over-writing it
Also updates the text to be more welcoming
stop text overwriting cupcake
**Other info**
Closes #602 
Closes #604
=> stop text overwriting cupcake

.github/workflows/ci.yaml, .github/workflows/deploy.yaml
By adding if check to these two jobs it will prevent spurious errors been reported from forked repos. 
Closes #616
=> GitHub Actions: Limit run to source repo

td.server/src/config/routes.config.js, td.server/test/config/routes.config.spec.js, td.vue/src/router/git.js, td.vue/src/service/api/threatmodelApi.js, td.vue/src/store/modules/threatmodel.js, td.vue/src/views/NewThreatModel.vue, td.vue/src/views/ThreatModelEdit.vue, td.vue/tests/unit/store/modules/threatmodel.spec.js, td.vue/tests/unit/views/newThreatModel.spec.js
**Summary**
This PR fixes #631
Allow the creation of a threat model while using GitHub as a provider by making the ThreatModelEdit call the create method of the server when on /create url.
**Other info**
- Creation of ThreatModelCreate (/crete) url for ThreatModelEdit component to differentiate when on creation from editing a threat model.
- Change THREATMODEL_CREATE action of the threatmodel store so the new threat model gets created.
- Creation of createAsync method on threatmodelApi to call /create api endpoint.
- Change from PUT to POST of /create api endpoint of server routes.
=> Fix #631 error while creation of threat model when using GitHub

td.vue/src/components/printed-report/ReportEntity.vue, td.vue/src/components/report/ReportEntity.vue, td.vue/tests/unit/components/printed-report/reportEntity.spec.js, td.vue/tests/unit/components/report/reportEntity.spec.js
**Summary**
The diagram threat attributes are added to both the printed report and the PDF report
add threat type and score to report
**Other info**
closes #646
=> add threat type and score to report

td.vue/src/components/SelectionPage.vue, td.vue/src/service/api/api.js, td.vue/src/service/api/threatmodelApi.js, td.vue/src/service/provider/providers.js, td.vue/src/store/modules/branch.js, td.vue/src/store/modules/provider.js, td.vue/src/store/modules/repository.js, td.vue/src/views/git/BranchAccess.vue, td.vue/src/views/git/RepositoryAccess.vue, td.vue/src/views/git/ThreatModelSelect.vue, td.vue/tests/unit/service/api/api.spec.js, td.vue/tests/unit/service/api/threatmodelApi.spec.js, td.vue/tests/unit/store/modules/branch.spec.js, td.vue/tests/unit/store/modules/provider.spec.js, td.vue/tests/unit/store/modules/repository.spec.js, td.vue/tests/unit/views/branchAccess.spec.js, td.vue/tests/unit/views/repositoryAccess.spec.js
**Summary**:
Adds pagination to repository and branch selection screen. Currently only the first ~30 repositories a user has access to are shown with no way to view others. Fixes issue with repo URI being hardcoded to github.com on the same screens.
Adds pagination to repository and branch selection screens.
closes #547 
=> add repo select page query param

td.vue/src/components/ProviderLoginButton.vue
**Summary**:
Small edge case race condition occurs when user logs out and then without refreshing clicks the local login button resulting in the provider not being set yet. This is due to a new async call being made in the provider selection action which would allow the dashboard render to occur before the provider state mutation was committed. 
Add await to provider selection call to fix log out and network call cache edge case.
Bug introduced in #688 
=> Add await to provider selection call

td.vue/src/views/ThreatModelEdit.vue
**Summary**:
When editing the threat model, the diagram attributes were displayed in two columns, which did not leave enough space for viewing the diagram descriptions
one diagram per line when adding to threat model
closes #699
=> diagrams added on individual rows

td.vue/src/views/ThreatModelEdit.vue
**Summary**:
The report feature crashed if the diagram had no cells defined, this pull request fixes this bug
bugfix for report crash on empty diagram
closes #704
=> bugfix for report crash on empty diagram

td.server/src/controllers/threatmodelcontroller.js, td.server/src/env/Github.js, td.server/src/repositories/threatmodelrepository.js
**Summary**:
This is somewhat of a rough PoC for enabling the use of GitHub repo search, rather than relying on a list of all repos accessible to the user. In the future, there might be a more user-friendly way to do this.
This adds:
- Two new GitHub-related env vars:
- `GITHUB_USE_SEARCH`: if `true`, uses octonode's `search.reposAsync` instead of `reposAsync` passing in a search query
- `GITHUB_SEARCH_QUERY`: specifies the search query to use when searching for repos for Threat Dragon to use
- A conditional check in `threatmodelcontroller` determines whether to use `reposAsync` _or_ `search.reposAsync` based on the above.
- A wrapper function in `threatmodelrepository` to use octonode's `search.reposAsync`, passing in the aforementioned search query. …
=> Add GitHub search option/feature for #733

td.vue/src/components/GraphProperties.vue, td.vue/src/service/x6/graph/data-changed.js, td.vue/src/service/x6/graph/events.js, td.vue/src/service/x6/shapes/trust-boundary-curve.js, td.vue/tests/unit/components/graphProperties.spec.js, td.vue/tests/unit/service/x6/graph/events.spec.js
**Summary**:
Various problems exist with selecting nodes and edges in the diagram:
* a bg where selecting a threat boundary curve throws an error
* clicking / selecting a node does not update the attributes
* moving a node does not update the attributes
fix bug where selecting a threat boundary curve throws an error
=> fix bug where selecting a threat boundary curve throws an error

td.vue/src/components/GraphProperties.vue, td.vue/src/service/x6/graph/data-changed.js, td.vue/src/service/x6/graph/events.js, td.vue/tests/unit/components/graphProperties.spec.js, td.vue/tests/unit/service/x6/graph/events.spec.js
**Summary**:
This fixes the broken unit tests by checking for null cell data
Also fixes an error thrown when an empty cell is selected after updating a previous cell
fix for errors thrown when selecting graph components
=> Fix for errors thrown when selecting graph components

td.vue/src/components/GraphProperties.vue, td.vue/src/service/x6/graph/data-changed.js, td.vue/src/service/x6/graph/events.js, td.vue/tests/unit/service/x6/graph/events.spec.js
**Summary**:
This fixes a bug where data flows and trust boundary curves can lose their names if the cell is unselected
ensure dataflow and trust boundary names are kept
closes #765
=> Ensure dataflow and trust boundary names are kept

td.server/src/repositories/threatmodelrepository.js
**Summary**:
With `GITHUB_USE_SEARCH` was enabled, calling `searchAsync` threw an error, as the `page` parameter was being passed in first (but wasn't used in the function).
- Fix `searchAsync` to enable repo search to work (and use pagination) correctly
=> Fix searchAsync to *actually* use the access_token (and pagination) correctly

td.vue/jest.config.js, td.vue/src/components/GraphProperties.vue, td.vue/src/service/x6/graph/data-changed.js, td.vue/src/service/x6/graph/events.js, td.vue/src/service/x6/shapes/index.js, td.vue/src/views/ThreatModelEdit.vue, td.vue/tests/unit/service/x6/graph/events.spec.js
**Summary**:
This fixes the bug when a node is already selected, and then a new data flow added, the selected node's properties are overwritten as data-flow properties
fix bug that overwrites node properties when adding dataflows
Closes #786 
Closes #768
=> fix bug that overwrites node properties when adding dataflows

td.server/package-lock.json, td.server/src/config/routes.config.js, td.server/src/controllers/configcontroller.js, td.server/src/controllers/responseWrapper.js, td.server/test/config/routes.config.spec.js, td.vue/src/store/actions/config.js, td.vue/src/store/index.js, td.vue/src/store/modules/config.js, td.vue/src/views/HomePage.vue, td.vue/tests/unit/views/homePage.spec.js
**Summary**:
As a pre-req for #426 and #61 enabling the homepage to only render login options that are configured. Ignored for Electron. 
Select which login options to render based on the configured environment variables, currently this is a check if the related **_CLIENT_ID is configured. 
Environment variables likely require refactoring.
=> Server config driven providers on HomePage.vue

td.vue/src/components/Graph.vue, td.vue/src/components/GraphButtons.vue, td.vue/src/i18n/en.js, td.vue/src/service/openThreatModel.js, td.vue/src/service/save.js, td.vue/src/store/modules/threatmodel.js, td.vue/src/views/ImportModel.vue, td.vue/tests/unit/components/graph.spec.js, td.vue/tests/unit/components/graphButtons.spec.js, td.vue/tests/unit/service/openThreatModel.spec.js, td.vue/tests/unit/service/save.spec.js
- Enhances the web application interface to allow for the import and export of threat models in the OTM format.
- resolves #440
**Summary**:
This change resolves issue #440 by adding import and export capabilities for threat models in the Open Threat Model format. The feature specifically targets the web applications Open and Save functions and allows for the conversion between the Threat Dragon format and the OTM 2.0 format.
Added Open and Save feature to the web application to support threat models in the Open Threat Model (OTM) format.
Change required updates to existing unit test cases and a new test case was created to cover the OTM conversion methods.
Please make sure you follow our …
=> feat: Adds Open Threat Modeling (OTM) support

td.vue/src/desktop/menu.js, td.vue/src/i18n/de.js, td.vue/src/i18n/el.js, td.vue/src/i18n/en.js, td.vue/src/i18n/es.js, td.vue/src/i18n/fi.js, td.vue/src/i18n/fr.js, td.vue/src/i18n/hi.js, td.vue/src/i18n/pt.js, td.vue/src/i18n/ru.js, td.vue/src/i18n/uk.js, td.vue/src/i18n/zh.js, td.vue/src/views/ReportModel.vue
**Summary**:
Creates a new desktop submenu for Export actions, and puts the HTML and PDF report functions under it
create desktop sub-menu for export functions
=> Create desktop Export sub-menu

td.vue/src/components/LocaleSelect.vue, td.vue/tests/unit/components/localeSelect.spec.js
**Summary**:
This PR changes the way languages are getting rendered. Initially the languages in the locale select dialog box was getting rendered by 3 letter ISO codes but now they have been locally transliterated into the respective language.
The update fixes a part of all the issues mentioned in #806. This PR changes the way languages are getting rendered.
language selection dropdown menu uses natural language
**Other info**:  
closes #806
=> made language selection understandable

td.vue/public/preload.js, td.vue/src/components/Graph.vue, td.vue/src/desktop/desktop.js, td.vue/src/desktop/menu.js, td.vue/src/main.desktop.js
**Summary**:
Prompts the user to save the model before quitting. Solves #846 
Controlled the way Electron was closing the app previously. However, the guard on the route to #/dashboard has not been implemented yet. We can address this in a separate issue to better organize the code.
=> Prompt user to save model before quitting the app

td.vue/src/components/DashboardAction.vue
**Summary**:
made changes in order to make whole dashboard-action block clickable and after making changes our dashboard-action panel will be looking like below
[screen-capture (1).webm](https://github.com/OWASP/threat-dragon/assets/107138786/750cc58c-573e-4407-859d-b295ddc21f23)
fixes: dashboard action
Fixes : #871
=> Fixes:dashboard action

td.vue/src/components/ThreatEditDialog.vue
**Summary**:
provides space for Buttons in Threat Edit Page
provide space for Buttons in Threat Edit Page
Fixes: #897
=> Fix:Buttons in Threat Edit Page

.github/workflows/pull_request.yaml, .github/workflows/push.yaml, .github/workflows/release.yaml, release-process.md
**Summary**:
Builds Docker images also for ARM. Improves developer experience on newer Macs with ARM CPU (Mx)
Adds necessary changes to the affected GitHub workflows
add build for arm64 docker image in GitHub workflows
The extra build time should be bearable, if not the builds for each arch can be run in parallel using a [matrix](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs).
=> Also build for arm64

td.vue/src/components/Graph.vue, td.vue/src/components/GraphMeta.vue, td.vue/src/components/GraphThreats.vue, td.vue/src/components/ThreatEditDialog.vue, td.vue/src/service/threats/index.js, td.vue/tests/unit/components/graph.spec.js, td.vue/tests/unit/components/graphMeta.spec.js, td.vue/tests/unit/components/graphThreats.spec.js
**Fixed the following issues**:
- (bug title is not updated with number after creation without saving) 
- (changes should not be preserved when retained threat next displayed)
**How does the addressed issues function now**:
now the number of the threat is added when it's created and the content of the threat in the cell is not changed unless saved so the unsaved changes are not retained when the threat is going to get edited again
Fixes some points addressed in #899 
Closes #899 
Closes #889
=> Creation of threats made consistent

td.vue/src/components/LocaleSelect.vue, td.vue/src/desktop/menu.js, td.vue/src/i18n/index.js, td.vue/src/i18n/ja.js, td.vue/tests/unit/components/localeSelect.spec.js
**Summary**:
Adds translation file and tests for Japanese, ISO 639-2 code 'jpn', ISO 639-1 code 'ja'.
Japanese sentence structure is different from English, so where a sentence is split over multiple strings, the individual strings do not match, but the sentence as a whole does.
Add Japanese translation
Closes #932
=> i18n: Add Japanese translation

td.vue/src/views/ReportModel.vue
**Summary**:
When on the report page, scrolling down the content causes the report options bar to move upwards slightly. Additionally, the report options bar appears above the language selection drop-down menu in the nav bar.
This change tweaks the CSS to correct the heights and margins of the report options bar so that it does not move and it changes the z-index of the report options bar to place it below the language drop-down.
Before:
After:
=> Stop report options moving and obscuring language drop-down

ThreatDragonModels/demo-threat-model.json, ThreatDragonModels/v2-threat-model.json, td.vue/src/service/demo/demo-threat-model.js, td.vue/src/service/demo/v2-threat-model.js, td.vue/tests/e2e/fixtures/v1-model.json
**Summary**:
This pull request fixes some minor typos in the threat descriptions of the demo models (and a test fixture). These aren't critical in the sense that they'd distort the meaning, but the fix may help to improve the first impression of Threat Dragon.
Fix typos in demo threat descriptions
Based on my understanding of the end-to-end test that uses the fixture in question ([`td.vue/tests/e2e/specs/threatmodel/import.cy.js`](https://github.com/OWASP/threat-dragon/blob/01b1bcc35365bb376e81aba3a480f2789a122660/td.vue/tests/e2e/specs/threatmodel/import.cy.js#L83)), the change shouldn't have any effect on the test because the changed description isn't checked. The test is also skipped at the moment.
=> Fix typos in demo threat descriptions

td.vue/src/service/x6/shapes/index.js
**Summary**:
This change should fix the undo of edges in the model. Both when deleting a node with connected edges and a single edge.
Here is the undo behavior before this change (on the public website):
https://github.com/OWASP/threat-dragon/assets/1309462/20b4f66a-b992-4454-873c-48c83c1af27f
Here is the undo behavior after this change (locally hosted):
https://github.com/OWASP/threat-dragon/assets/1309462/033493f5-3991-4715-989b-e07df08145b9
Register Edges in the x6 model instead of registering Edges as Nodes.
Closes #428
Line 14 might need a similar change, but I am not familiar with the compatibility concerns.
=> Fix undo for edges

td.server/src/env/Bitbucket.js, td.server/src/env/Github.js, td.server/src/env/Gitlab.js, td.server/src/env/ThreatDragon.js, td.server/src/repositories/bitbucketrepo.js, td.server/src/repositories/githubrepo.js, td.server/src/repositories/gitlabrepo.js, td.server/test/repositories/bitbucketrepo.spec.js, td.server/test/repositories/gitlabrepo.spec.js
**Summary**:
As per the documentation found here: https://owasp.org/www-project-threat-dragon/docs-2/getting-started#opening-an-existing-model
> Note that Threat Dragon is fairly strict on where the threat models can be stored. The threat models must be under a parent directory called ‘ThreatDragonModels’ and the JSON file must then be stored in a sub-directory with the same name as the model.
> As an example, shown is a directory containing two models ‘test-reports’ and ‘New Threat Model’ under the directory ‘ThreatDragonModels’. This directory structure has been carried over from Threat Dragon versions 1.x, and in future it may become less strict.
I was hoping there would be a way of configuring where saved models are stored on a repo (ie in a `/doc` directory), and seeing this thought …
=> Set model storage path via env var

.github/workflows/pull_request.yaml, .github/workflows/push.yaml, .github/workflows/release.yaml
**Summary**:
something with the docker SBOM gathering failed. see https://github.com/OWASP/threat-dragon/actions/runs/9203973802/job/25316590644#step:8:1
here is a possible fix.
fix CI pipeline for docker SBOM.
followup of #964
=> ci: fix docker SBOM gathering

td.server/src/providers/gitlab.js
**Summary**:
Closes #995 
The scope params default value is separated by spaces instead of commas as defined by [the oauth spec](https://datatracker.ietf.org/doc/html/rfc6749#section-3.3).
=> Aligned scope param default value with oauth spec

td.server/src/providers/gitlab.js, td.server/src/repositories/gitlabrepo.js, td.vue/src/components/ThreatEditDialog.vue, td.vue/src/service/threats/index.js, td.vue/src/service/threats/models/index.js, td.vue/tests/unit/components/threatEditDialog.spec.js
Suggesting the type of the threat upon creation
works with all diagram models (except generic)
1- added a frequency mapping to keep track of threat type for each cell.
2- suggesting the least frequent type each time.
3- the map won't be attached to the element until it has a saved threat first.
Related to the issues #987 and #985
=> [Feature]: Threat type suggestion

.github/workflows/housekeeping.yaml, .github/workflows/pull_request.yaml, .github/workflows/push.yaml, .github/workflows/release.yaml, td.vue/package-lock.json, td.vue/package.json
**Summary**:
updates pipeline dependencies for :
* aquasecurity/trivy-action to 0.23.0
* docker/build-push-action to 6.3.0
overrides td.vue braces to be >= 3.0.3
update pipeline dependencies
=> update pipeline dependencies

td.server/src/controllers/auth.js, td.server/src/controllers/threatmodelcontroller.js, td.server/src/repositories/gitlabrepo.js
**Summary**:
Fixes [Issue 1001](https://github.com/OWASP/threat-dragon/issues/1001)
The two env vars GITHUB_SEARCH_QUERRY and GITHUB_USE_SEARCH renamed to REPO_SEARCH_QUERRY and REPO_USE_SEARCH respectively to better reflect that they are applied for every repo integration.
Fixed the searchAsync method of the gitlabrepo to work properly.
some envs renamed and searchAsync fixed for gitlabrepo
=> fix: SEARCH envs renamed and searchAsync fixed for gitlabrepo

td.server/src/repositories/gitlabrepo.js, td.vue/src/App.vue, td.vue/src/service/migration/diagram.js, td.vue/src/service/schema/ajv.js, td.vue/tests/e2e/support/e2e.js, td.vue/tests/unit/app.spec.js
**Summary**:
Only show warning about version 1.x files being moved to version 2.x if the file is at version 1.x
Otherwise keep quiet and do not scare the users
show v1.x warning only when opening v1.x diagrams
closes #1005 
this came about after hearing the feedback from Threat Model Connect conference in Lisbon 2024
=> do not scare the users with version 1.x warnings

td.server/src/repositories/gitlabrepo.js, td.vue/src/service/x6/shapes/trust-boundary-box.js, td.vue/src/service/x6/shapes/trust-boundary-curve-stencil.js, td.vue/src/service/x6/shapes/trust-boundary-curve.js, td.vue/tests/unit/service/x6/shapes/trust-boundary-box.spec.js, td.vue/tests/unit/service/x6/shapes/trust-boundary-curve.spec.js
**Summary**:
trust boundaries looked too much like an out of scope diagram element, so use a heavier dash ratio for trust boundaries
trust boundaries given heavier dash ratio
closes #1006
=> trust boundaries given heavier dash ratio

.github/workflows/browserstack.yaml, .github/workflows/pull_request.yaml, .github/workflows/push.yaml, .github/workflows/release.yaml
**Summary**:
Updates docker builds in the workflows:
* temporary fix for very large docker caches
* pull-requests no longer need permissions to use docker secrets
workflow docker builds fixed for large caches and pull-request permissions
closes #982
=> Fixes for workflow docker builds 

td.server/src/controllers/auth.js, td.server/src/controllers/errors.js, td.server/src/controllers/threatmodelcontroller.js, td.server/src/helpers/logger.helper.js, td.server/test/helpers/logger.helper.spec.js
**Summary**:
This PR attempts to solve issue, and closes #1010  
Objects are being preprocessed before logging, so that circularities can be removed.
New method for logger to handle circular objects before logging.
=> fix: logger can handle circular objects

td.server/src/controllers/threatmodelcontroller.js, td.server/src/env/Github.js, td.server/src/env/ThreatDragon.js, td.server/test/env/ThreatDragon.spec.js
**Summary**:
The renamed env vars REPO_USE_SEARCH and REPO_SEARCH_QUERY have not been processed by the application, because the app still expected to load env vars calles GITHUB_USE_SEARCH and GITHUB_SEARCH_QUERY.
So I moved the two env vars from the **env/Github.js** file to the general **env/ThreatDragon.js** file...
Additionally the gitlab search does not return an object with an atribute named items but simply just an array.
So i slightly tweak the `threadmodelcontroller` to handle the return value accordingly..
Fixes #1001 
=> fix: REPO_SEARCH envs are processed by the application

td.vue/src/service/api/threatmodelApi.js, td.vue/tests/unit/service/api/threatmodelApi.spec.js
**Summary**:
Some url params are now properly encoded, so that threat-dragon can handle deeply nested repositories.
Fixes #1003 
encode url params to handle deeply nested repositories
=> Encode url params to handle deeply nested repositories

td.vue/src/desktop/menu.js
**Summary**:
The pdf extension is incorrect when saving files in the desktop app
correct pdf extension when saving file
fixes #1023
=> correct pdf extension when saving file

.github/workflows/browserstack.yaml, .github/workflows/pull_request.yaml, .github/workflows/push.yaml, .github/workflows/release.yaml, td.vue/src/desktop/menu.js, td.vue/tests/unit/desktop/menu.spec.js
**Summary**:
Electron for Linux and Windows does not implement 'recent files' or 'clear recent files', so make this specific for MacOS only
desktop recent file sub-menu only for MacOS
Only electron for MacOS [implements 'recent files'](www.electronjs.org/docs/latest/api/menu-item#roles)
Closes #990
=> desktop recent file sub-menu only for MacOS

.github/workflows/.zap-rules-web.tsv, .github/workflows/housekeeping.yaml, .github/workflows/pull_request.yaml, .github/workflows/push.yaml, .github/workflows/release.yaml, td.server/package-lock.json, td.server/package.json, td.server/src/app.js
**Summary**:
Updates various versions of workflow actions
Mark issues as stale after 190 days rather than 182 days
Applies content security policy (CSP) and closes #950 
ZAP scan rules cleaned up, closes #945 
update workflows for versions and staleness
also tested issue and fixes #629, provided in update to documentation commit [d11919ad](https://github.com/OWASP/www-project-threat-dragon/commit/d11919adf1c96b58383dc754dfd24e3d6ffd07ff)
=> update workflows for versions and staleness

td.vue/src/service/schema/threat-model-schema.V2.js
**Summary**:
This Pull Request solved the issue: closes #1046 
I have changed the type in the Schema for the `vertices` types to be able to accept decimals, tested it locally and it succesfully imports a model where the x or y vertices are decimals.
=> Change vertices properties from integer to number so they can be imported

td.vue/src/components/KeyboardShortcuts.vue, td.vue/src/i18n/ar.js, td.vue/src/i18n/de.js, td.vue/src/i18n/el.js, td.vue/src/i18n/en.js, td.vue/src/i18n/es.js, td.vue/src/i18n/fi.js, td.vue/src/i18n/fr.js, td.vue/src/i18n/hi.js, td.vue/src/i18n/id.js, td.vue/src/i18n/ja.js, td.vue/src/i18n/ms.js, td.vue/src/i18n/pt.js, td.vue/src/i18n/ru.js, td.vue/src/i18n/uk.js, td.vue/src/i18n/zh.js, td.vue/src/service/x6/graph/keys.js, td.vue/tests/unit/service/x6/graph/keys.spec.js
**Summary**:
Adds the ctrl+s keyboard shortcut to save the diagram. Closes #1066 
Added ctrl+s shortcut for saving
=> Add ctrl+s to save graph

td.vue/package.json, td.vue/src/service/migration/diagram.js, td.vue/src/service/x6/graph/graph.js, td.vue/tests/unit/service/x6/graph/graph.spec.js
**Summary**:
helps to debug the bug where canvas does not resize properly when opening and saving a diagram
set autoResize true for graph diagram
related to #1041 but does not close it
=> set autoResize true for graph diagram

td.vue/browserstack.nightly.json, td.vue/browserstack.smokes.json, td.vue/package-lock.json, td.vue/package.json
**Summary**:
Updates for BrowserStack tests:
- remove macOS Big Sur
- add support for macOS Ventura
Note that BrowserStack does not support Opera or macOS Sonoma (yet)
update platform and browser list for BrowserStack tests
closes #1108
=> Update BrowserStack platform and browser list

td.vue/src/service/save.js
**Summary**:
Use File System Access API supported by Chrome/Chromium, Edge and most browsers except Safari
use File System Access API if supported on the browser
closes #643 
tested with Chrome and Safari to get both use cases
=> use File System Access API if supported on the browser

td.vue/src/components/GraphMeta.vue, td.vue/src/components/GraphThreats.vue, td.vue/src/components/ThreatSuggestDialog.vue, td.vue/src/service/migration/diagram.js
**Summary**:
Only enables contextual/type threat suggestions when new threat button is enabled, otherwise disabled
fix for type/context errors on edges and nodes that are out of scope
closes #1110
=> fix for type/context errors

.github/workflows/release.yaml, .release-note-template.md, release-process.md
**Summary**:
Update the release pipeline to use notary tool via :
- APPLE_ID
- APPLE_APP_SPECIFIC_PASSWORD
- APPLE_TEAM_ID
use notarytool for MacOS images
Closes #978
=> Update release pipeline for notarytool

.github/workflows/housekeeping.yaml, .github/workflows/pull_request.yaml, .github/workflows/push.yaml, release-process.md
**Summary**:
Trivy download is not stable enough, and the pipeline action randomly fails
disable trivy until it can be reliably downloaded
=> disable trivy until it can be reliably downloaded

.github/workflows/push.yaml, .github/workflows/release.yaml
**Summary**:
Update `actions/download-artifact` in workflows to consistently use 4.1.8.
Fixes #1136
Update actions/download-artifact in workflows to consistently use 4.1.8.
4.1.8 is the current latest (at the time of submission): https://github.com/actions/download-artifact/releases
=> Update actions/download-artifact to consistently use 4.1.8

td.server/package-lock.json, td.server/package.json, td.server/test/config/parsers.config.spec.js
**Summary**:
Upgrades Express to version 5.x
Upgrade to Express@5
=> Upgrading to Express v5

td.server/src/controllers/threatmodelcontroller.js, td.server/src/repositories/bitbucketrepo.js, td.server/src/repositories/githubrepo.js, td.server/src/repositories/gitlabrepo.js, td.vue/src/components/SelectionPage.vue, td.vue/src/service/api/threatmodelApi.js, td.vue/src/store/modules/repository.js, td.vue/src/views/git/BranchAccess.vue, td.vue/src/views/git/RepositoryAccess.vue, td.vue/tests/unit/service/api/threatmodelApi.spec.js
Summary:
This pull request fixes an issue with the repository search functionality when performing threat modeling in an existing repository connected to a GitLab server with many repositories. The issue caused the search results to display a blank page if the desired repository was on a second or subsequent page.
Description for the changelog:
Fix repository search functionality to dynamically fetch results from the Git provider after 500ms when the search query changes.
Other info:
This fix ensures that every time the search input is updated, a new API call is made with the updated search query after a 500ms debounce. The updated results are then fetched from the Git provider, ensuring that repositories are displayed correctly regardless of their pagination.
=> fix broken repository search

td.vue/src/components/ThreatSuggestDialog.vue
**Summary**:
Fix Issue #1183 
- Forces Id renewal on suggestion acceptance
closes #1183 
=> Fix id duplication on ThreatSuggestDialog

.github/workflows/.trivyignore, td.vue/src/service/x6/shapes/actor.js, td.vue/src/service/x6/shapes/trust-boundary-box.js, td.vue/tests/unit/service/x6/shapes/trust-boundary-box.spec.js
**Summary**:
The trust boundary boxes label was no longer visible after moving to AntV/X6 version 2.x, probably due to some incompatibility wioth version 1.x
make label visible for trust boundary box
This issue was introduced in Threat Dragon version 2.3
fixes #1160
=> Reinstate the label text for trust boundary boxes

td.vue/src/service/x6/graph/graph.js
**Summary**:
Reinstates the resizing of graph diagram nodes, this was a regression from the upgrade to AntV/X6 version 2.x
reinstate diagram node resizing
=> reinstate diagram node resizing

td.vue/jest.config.js, td.vue/package-lock.json, td.vue/package.json, td.vue/src/service/migration/diagram.js, td.vue/vue.config.js
**Summary**:
Provides passive events support to touchstart and mousewheel events in the diagram, which prevents the warnings :
- "Added non-passive event listener to a scroll-blocking 'mousewheel' event."
- "Added non-passive event listener to a scroll-blocking 'touchstart' event."
also removes client webSocketURL from Vue devServer config due to error on the console for the desktop app:
- "WebSocket connection to 'wss://localhost/ws' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED"
clean up console of warnings and errors
closes #1100
=> clean up console of warnings and errors

example.env, td.vue/vue.config.js
**Summary**:
When we added native TLS support to Threat Dragon, we used two environment variables for the host name - one for the app to use and one for TLS certificate validation.  This is unnecessarily complex and error prone, and we have not identified a use case where the names need to be different, so we're consolidating into a single environment variable.
Remove APP_HOSTNAME_TLS, just use APP_HOSTNAME instead
=> consolidating hostname variable

td.vue/src/service/demo/v2-new-model.js, td.vue/src/service/x6/graph/data-changed.js, td.vue/src/service/x6/graph/events.js, td.vue/src/service/x6/shapes/flow-stencil.js, td.vue/src/service/x6/shapes/flow.js, td.vue/src/service/x6/shapes/trust-boundary-curve-stencil.js, td.vue/src/service/x6/shapes/trust-boundary-curve.js, td.vue/src/views/NewThreatModel.vue, td.vue/src/views/git/ThreatModelSelect.vue, td.vue/tests/unit/service/x6/graph/events.spec.js
**Summary**:
The labels for  data flow and trust boundary curve can not be used to select the edge - it would be _**very**_ useful if they could
also the labels can be obscured by the line passing through them - this needs whitespace around the label
flow and trust boundary labels made legible and selectable
also applies a select box around the flow stencil and trust boundary curve stencil, for easier selection of these stencils
closes #1198 
although it does not solve #1174 , this is the best we can do. If the verticex change event is used to select the data flow then the vertex no longer becomes available for change. This comes from AntV/X6 and is unlikely to change
closes #1174
=> Make edge labels legible and selectable

td.vue/vue.config.js
Prefers the environment variable named "SERVER_API_PORT".  If this value is falsy, then uses the environment variable "PORT" for backwards compatibility.  If this value is falsy, then use the default value of 3000.
**Summary**:
=> Rename "PORT" environment variable to "SERVER_API_PORT"

.lycheeignore, td.vue/src/service/x6/shapes/trust-boundary-box.js
**Summary**:
Bug fix for unexpected label on Trust Boundary Box - does nto apply the label 'Trust Boundary Box' when this label did not appear before
Bug fix for unexpected label on Trust Boundary Box
closes #1230
=> Bug fix for unexpected label on Trust Boundary Box

example.env, td.server/src/app.js, td.server/src/env/ThreatDragon.js, td.server/src/healthcheck.js, td.server/test/env/ThreatDragon.spec.js, td.vue/vue.config.js
Reverts OWASP/threat-dragon#1228
backing out changes that stop Heroku demo site from running:
heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
=> Revert: Clean up, add error checking, remove ambiguity around term "port"

.github/workflows/.trivyignore, td.vue/src/i18n/ar.js, td.vue/src/i18n/de.js, td.vue/src/i18n/el.js, td.vue/src/i18n/en.js, td.vue/src/i18n/es.js, td.vue/src/i18n/fi.js, td.vue/src/i18n/fr.js, td.vue/src/i18n/hi.js, td.vue/src/i18n/id.js, td.vue/src/i18n/ja.js, td.vue/src/i18n/ms.js, td.vue/src/i18n/pt.js, td.vue/src/i18n/ru.js, td.vue/src/i18n/uk.js, td.vue/src/i18n/zh.js, td.vue/src/main.desktop.js, td.vue/src/service/demo/huskyai.tmbom.json, td.vue/src/service/demo/index.js, td.vue/src/service/migration/tmBom/diagrams/boxes.js, td.vue/src/service/migration/tmBom/diagrams/nodes.js, td.vue/src/service/migration/tmBom/diagrams/threats/risks.js, td.vue/src/service/migration/tmBom/threat-model.schema.json, td.vue/src/views/ImportModel.vue, td.vue/src/views/demo/SelectDemoModel.vue, td.vue/tests/unit/service/demo/index.spec.js, td.vue/tests/unit/service/migration/tmBom/diagrams/nodes.spec.js, td.vue/tests/unit/views/demo/selectDemoModel.spec.js
**Summary**:
Allow Threat Dragon to import TM-BOM schema files. Export to follow later in 2025
Adds a sample TM-BOM into the demos as Husky AI
enable TM-BOM import
task for issue #850
=> Enable TM-BOM import

td.vue/src/service/x6/graph/keys.js
**Summary**:
Saving via keyboard shortcut doesn't apply the current diagram to the threatmodel state, so when the model saves, it saves whatever was already in it, which is what's currently on the disk. This is probably the cause of https://github.com/OWASP/threat-dragon/issues/1254. Saving via the File menu or the Save icon work correctly by applying the diagram to the threatmodel state first, so just replicate that.
Dispatch `THREATMODEL_DIAGRAM_APPLIED` before dispatching `THREATMODEL_SAVE` when saving via keyboard shortcut.
Steps to reproduce:
1. Open a diagram.
2. Make a trivial change (add a new process).
3. Save via ctrl+s.
Expected:
Output json file contains expected changes.
Actual:
Output json file is identical …
=> Fix saving with keyboard shortcut so that it actually saves new data
