OWASP/threat-dragon

.codeclimate.yml
README.md

**- Summary**
Travis now pointing to this repo
Removed Code Climate as this requires a licence fee
Removed Dependency as this requires a licence fee from Tidelift
**- Tests**
Travis build passing on this PR
**- Description for the changelog**
Update CI tests
**- Any other info**

update CI tests

---

td/public/app/threatmodels/github.js

**- Summary**
There is a [LGTM alert](https://lgtm.com/projects/g/OWASP/threat-dragon/alerts/?mode=list) that shows a function not returning a value
**- Tests**
tests still pass
**- Description for the changelog**
fixed LGTM alert in function getLocation
**- Any other info**

fixed LGTM alert in function getLocation

---

.snyk
package.json

**- Summary**
Some security updates to third party packages
**- Tests**
normal automated tests should be enough
**- Description for the changelog**
update packages for security fixes
**- Any other info**

update packages for security fixes

---

.snyk
README.md
package.json

**Summary**
Snyk is proving too problematic
remove Snyk
**Other info**
use a different dependency  analysis

remove Snyk

---

td/config/routes.config.js

**Summary**
Added a really simple health check endpoint that can be used to configure deployment probes 
Add `/healthz` endpoint for liveness / readiness checks
**Other info**

feat: added healthz endpoint

---

.gitignore

**Summary**
ignore IntelliJ IDEA files
ignore IntelliJ IDEA files

ignore IntelliJ IDEA files

---

.github/workflows/zap_scan.yaml

**Summary**
Made the ZAP - Baseline Scan run on pull/push requests through GitHub Actions
Added the ZAP - Baseline Scan to the project

Add ZAP - Baseline Scan 

---

CONTRIBUTING.md
dev-notes.md

**Summary**
Keep main branch up to date with some version 2.0
Update contribution notes
**Other info**

Version2.0

---

td.vue/TODO
td.vue/src/components/Graph.vue
td.vue/src/service/migration/diagram.js
td.vue/src/service/x6/graph/data-changed.js
td.vue/src/service/x6/shapes/actor.js
td.vue/src/service/x6/shapes/process.js
td.vue/src/service/x6/shapes/store.js
td.vue/src/service/x6/shapes/text.js
td.vue/src/service/x6/stencil.js
td.vue/tests/unit/service/migration/diagram.spec.js
td.vue/tests/unit/service/x6/graph/data-changed.spec.js
td.vue/tests/unit/service/x6/shapes/text.spec.js
td.vue/tests/unit/service/x6/stencil.spec.js

Incremental checkin to kick off auto-deploy.
Implementing changes from #150 #189 and #128 
- Transparent background for free-text node/label
- Elements with threats are now bold and red
- Added protocol to label for data flows

V2/diagram UI

---

.dockerignore
README.md

**Summary**
A couple of small tidy ups for the docker image and how to run it
small tidy ups for docker image
**Other info**

small tidy ups for docker image

---

td.desktop/app/app.js
td.desktop/karma.conf.js
td.desktop/package-lock.json
td.desktop/package.json
td.desktop/test/spec/test.js

**Summary**
This removes the remaining dependency on owasp-threat-dragon-core package, described in #214 
remove dependency on external core package
**Other info**

remove dependency on external core package (issue #214)

---

td.site/src/app/core/diagrams/CiaEditPane.html
td.site/src/app/core/diagrams/LinddunEditPane.html
td.site/src/app/core/diagrams/StrideEditPane.html
td.site/src/app/core/templates.js

**Summary**
Add NA to the Threat Level selector for STRIDE/LINDDUN/CIA threats
Add NA as a Threat Level value, issue #195 
**Other info**
This can also be forward ported to version 2.0

Add NA as a Threat Level value

---

td.desktop/core/services/threatengine.js

**Summary**
Fix for broken threat generation per element, reported by @uncatchable-de in issue #258 
fix for broken threats per element #258 and refactor threat engine
**Other info**
This should go into version 1.5.1 as soon as practical

fix for broken threats per element #258 and refactor threat engine

---

td.desktop/app/welcome/welcome.js

**Summary**
This is a fix for #262 "Windows: Cannot find module .....demo-threat-model.json"
It fixes the path for cross platforms for both new-model.json and demo-threat-model.json
Bugfix for Windows: Cannot find module
**Other info**

Closes #262 Windows: Cannot find module

---

package-lock.json
td.desktop/core/diagrams/CiaEditPane.html
td.desktop/core/diagrams/LinddunEditPane.html
td.desktop/core/diagrams/StrideEditPane.html
td.desktop/core/diagrams/ThreatSummaryPane.html
td.desktop/core/templates.js

**Summary**
This is a bug fix for #271 'NA threats not shown as mitigated'
The threats marked NA will now have a green tick showing that they are resolved. The priority will be preserved:
threats marked NA shown as resolved
**Other info**

Bugfix: threats marked NA shown as resolved, close #271

---

td.vue/TODO
td.vue/src/store/modules/auth.js
td.vue/src/store/modules/threatmodel.js
td.vue/src/views/OauthReturn.vue
td.vue/src/views/ThreatModel.vue
td.vue/src/views/git/ThreatModelSelect.vue
td.vue/tests/unit/components/localeSelect.spec.js
td.vue/tests/unit/router/git.spec.js
td.vue/tests/unit/service/provider/local.provider.spec.js
td.vue/tests/unit/store/modules/auth.spec.js
td.vue/tests/unit/store/modules/threatmodel.spec.js
td.vue/tests/unit/views/diagram.spec.js
td.vue/tests/unit/views/newThreatModel.spec.js
td.vue/tests/unit/views/oauthReturn.spec.js
td.vue/tests/unit/views/threatmodel.spec.js
td.vue/tests/unit/views/threatmodelSelect.spec.js

**Summary**
Small refactor to make store actions more consistent between fetch and selected
**Other info**
Also improved test coverage a bit.

v2 - Chore: Store/action cleanup & test coverage

---

td.vue/src/i18n/index.js
td.vue/src/i18n/pt.js

**Summary**
Adds PT (or PT-BR) as a translation for v2
Adding PT-BR translation
**Other info**
Thanks to @marshallowitz and team for their work on this!

Adding PT translations provided in #297

---

td.vue/src/i18n/fr.js
td.vue/src/i18n/index.js

**Summary**
Provides translation from English to French.
#297 - Adding EN to FR translation
**Other info**
PR inspired from #315 🙂

Providing translation from English to French

---

package-lock.json
td.desktop/core/diagrams/ElementPropertiesPane.html
td.desktop/core/diagrams/ThreatSummaryPane.html
td.desktop/core/diagrams/diagram.js
td.desktop/core/diagrams/diagrameditor.html
td.desktop/core/diagrams/elementpropdirectives.js
td.desktop/core/diagrams/index.js
td.desktop/core/services/dialogs.js
td.desktop/core/services/joint.shapes.tm.js
td.desktop/core/services/threatengine.js
td.desktop/core/templates.js
td.desktop/test/core/diagrams/diagram_spec.js
td.desktop/test/core/diagrams/elementpropertydirectives_spec.js
td.desktop/test/core/services/threatengine_spec.js

**Summary**
This provides context based threat generation using the properties of the elements, such as 'Provides authentication' for an Actor element
experimental OWASP automated threat and context threat generation
**Other info**
Too big and rambling a change to be properly reviewed, so advised as 'experimental' in the application

Experimental OWASP automated threat and context threat generation

---

td.server/src/config/bearer.config.js
td.vue/package-lock.json
td.vue/src/i18n/es.js
td.vue/src/i18n/index.js

**Summary**
Adds es translation, as provided by @GigliolaCordova 
Adds es translation

Adding "es" translation

---

dev-notes.md

**Summary**
The dev notes needed minor updating for the new environment variables:
ENCRYPTION_KEYS
ENCRYPTION_JWT_SIGNING_KEY
ENCRYPTION_JWT_REFRESH_SIGNING_KEY
update dev notes for encryption key env vars
**Other info**
Very minor pull-request just to get the hang of it

update dev notes for encryption key env vars

---

td.vue/src/service/x6/graph/graph.js
td.vue/tests/unit/service/x6/graph/graph.spec.js

**Summary**
Adds scrolling to the graph
Closes #331 
Mousewheel works as expected.  Holding shift and using mousewheel will scroll horizontally.

Add scrolling

---

td.vue/src/i18n/cn.js
td.vue/src/i18n/index.js

**Summary**
What existing issue does the pull request solve?
Add Internationalization for China
Add cn.js file, modify i18n/index.js
fixes #350

The first Sinicization

---

README.md

**Summary**
Adds a notice about v1 EOL and where to find more information on running v1.x
Don't be afraid of providing feedback on this one! I just wanted to get the discussion/idea started, if there's a better way I am 100% behind it!

Adding EOL notice for v1 in README

---

td.server/package.json
td.vue/package.json

Changed homepage value in 'td.vue/package.json' and 'td.server/package.json

---

td.vue/src/components/Navbar.vue

**Summary**
navbar height was littlebit small and in tablet view the navbar was breaking.
increased the height by 10px now it looks neat.
**Other info**
its my first pr in owasp community looking forward to it

navbar height increased by 10

---

ThreatDragonModels/legacy_desktop_model/legacy_desktop_model.json

Fix some typos

---

docs/development/testing/e2e.md
docs/usage/collaboration/linking.md
td.vue/src/components/GraphMeta.vue
td.vue/src/components/ThreatCard.vue
td.vue/src/components/printed-report/ExecutiveSummary.vue
td.vue/src/components/report/ExecutiveSummary.vue
td.vue/src/i18n/en.js
td.vue/src/service/threats/models/index.js
td.vue/tests/unit/components/graphMeta.spec.js

**Summary**
This fixes some typos and adds some labels
fixup some labels
**Other info**
No need for review (unless you really want to) as this is very straight forward

fixup some labels

---

.gitignore
docs/development/env.md
td.server/dev.js
td.server/index.js
td.server/src/app.js
td.server/src/config/bearer.config.js
td.server/src/controllers/auth.js
td.server/src/controllers/healthcheck.js
td.server/src/controllers/homecontroller.js
td.server/src/controllers/threatmodelcontroller.js
td.server/src/env/Env.js
td.server/src/helpers/encryption.helper.js
td.server/src/helpers/logger.helper.js
td.server/src/providers/index.js
td.server/src/repositories/token.js
td.server/test/mocks/express.mocks.js
td.server/test/providers/github.spec.js

**Summary**
Extending logging though the Threat Dragon back-end server
logging extended within td.server
**Other info**

Server logging

---

td.vue/src/components/report/ExecutiveSummary.vue
td.vue/src/views/ThreatModel.vue

**Summary**
Fixed an issue where the Description item did not support multi-line display.
multi-line rendering of description. fixes #468 
**Other info**

fix: multi-line description

---

td.server/dev.js
td.server/index.js
td.server/src/config/bearer.config.js
td.server/src/controllers/auth.js
td.server/src/controllers/healthcheck.js
td.server/src/controllers/homecontroller.js
td.server/src/controllers/threatmodelcontroller.js
td.server/src/helpers/encryption.helper.js
td.server/src/repositories/token.js

**Summary**
_**temporary pull-request**_
**Other info**

revise logging to trace login request

---

td.vue/src/i18n/cn.js

Update chart Chinese translation

Update chart Chinese translation

---

README.md
docs/development/actions/about.md
docs/development/api.md
docs/development/local.md
docs/development/release-process.md
docs/home/about/conduct.md
docs/home/trust/container.md
docs/home/trust/dast.md
docs/home/trust/dependencies.md
docs/home/trust/incidents.md
docs/home/trust/sast.md
docs/home/trust/sbom.md
docs/usage/install/docker.md
td.server/package.json
td.server/src/healthcheck.js
utils/DragonExtractor/README.md

**Summary**
updates some docs and provide tables with detail on existing server API
update docs and provide details of server API
**Other info**

Docs update

---

docs/usage/install/docker.md

**Summary**
update docs page for docker build and run
update docs page for docker build and run
**Other info**

update docs page for docker build and run

---

docs/usage/install/docker.md

**Summary**
Windows users need some help with the working directory, and also we need to expand on debugging
update for debugging of docker containers
**Other info**

update for debugging of docker containers

---

td.vue/src/service/x6/stencil.js
td.vue/tests/unit/service/x6/stencil.spec.js
td.vue/vue.config.js

**Summary**
We need to temporarily remove the search feature until it is fully functional
temporary remove search feature for diagram elements
**Other info**

temporary remove search feature for diagram elements

---

td.vue/src/components/ThreatEditModal.vue
td.vue/src/i18n/en.js
td.vue/src/i18n/fr.js
td.vue/tests/unit/components/threatEditModal.spec.js

**Summary**
Users have requested that the threat Status and Priority be changed to radio buttons, to aid selection
change to radio buttons for threat status and priority
**Other info**

change to radio buttons for threat status and priority

---

td.vue/src/desktop/desktop.menu.js
td.vue/src/i18n/en.js

**Summary**
File Open and SaveAs dialogs added for Electron
add File Open and File SaveAs dialog boxes for desktop
**Other info**

add File Open and File SaveAs dialog boxes for desktop

---

td.vue/src/components/Graph.vue
td.vue/src/components/GraphProperties.vue
td.vue/src/service/x6/graph/data-changed.js

**Summary**
Need to update the diagram components when the properties change, otherwise they update only when focus is moved
update diagram component on property change
**Other info**

update diagram component and reason on scope change

---

td.vue/src/i18n/cn.js
td.vue/src/i18n/de.js
td.vue/src/i18n/el.js
td.vue/src/i18n/en.js
td.vue/src/i18n/fr.js
td.vue/src/i18n/hi.js
td.vue/src/i18n/index.js
td.vue/src/i18n/pt.js
td.vue/src/i18n/ru.js

**Summary**
It would be good to add further languages such as Russian (ru), German (de) and Hindi (hi)
update i18n and add DE, HI and RU
**Other info**

update i18n and add DE, HI and RU

---

td.vue/src/i18n/fr.js

**Summary**
This PR updates the existing French translation (I updated some words based on the context of the page) as well as the new additions from the English version.
French translation is updated for Version 2.0
**Other info**
Closes #530

Update french translation for v2

---

td.vue/src/i18n/en.js
td.vue/src/views/Import.vue

**Summary**
Improve the user experience when importing json files using local session, by making the textfield a dropzone. 
Implement dropzone for threat model imports.
**Other info**
There are no tests yet, contributions welcome.
Issue #543

Implement dropzone for threat model imports.

---

td.vue/src/i18n/cn.js
td.vue/src/i18n/de.js
td.vue/src/i18n/el.js
td.vue/src/i18n/en.js
td.vue/src/i18n/es.js
td.vue/src/i18n/fr.js
td.vue/src/i18n/pt.js
td.vue/src/i18n/ru.js
td.vue/src/store/modules/threatmodel.js
td.vue/src/views/ImportModel.vue
td.vue/tests/unit/views/importModel.spec.js

**Summary**
This makes the open-file behaviour same as the drop-file behaviour
align open-file with drop-file
**Other info**

align open-file with drop-file

---

td.vue/src/i18n/cn.js

**Summary**
This PR update the existing chinese translation (I update some words base on the context of the page).
Improve chinese translation for version 2.0

Improve chinese translation for version 2.0

---

td.vue/src/i18n/cn.js
td.vue/src/i18n/de.js
td.vue/src/i18n/el.js
td.vue/src/i18n/en.js
td.vue/src/i18n/es.js
td.vue/src/i18n/fr.js
td.vue/src/i18n/pt.js
td.vue/src/i18n/ru.js
td.vue/src/service/demo/demo-threat-model.js
td.vue/src/service/demo/v2-threat-model.js
td.vue/src/service/migration/diagram.js
td.vue/src/views/ThreatModel.vue
td.vue/src/views/ThreatModelEdit.vue
td.vue/tests/unit/views/threatmodel.spec.js
td.vue/tests/unit/views/threatmodelEdit.spec.js

**Summary**
Add a description for each diagram, so that on the main threat model page it is obvious which diagram is associated with which activity. Fixes [#553](https://github.com/OWASP/threat-dragon/issues/553)
[#553](https://github.com/OWASP/threat-dragon/issues/553) - Add description field on thread model edit page and replace the threat model image with the newly added description.
**Other info**
Nothing else to add.

Provide diagram description Fix

---

docs/development/internationalization.md
td.vue/src/desktop/menu.js
td.vue/src/i18n/hi.js
td.vue/src/i18n/index.js
td.vue/src/i18n/zh.js

**Summary**
Revise the language codes to follow BCP 47 and add the translation list to the documentation
update language codes and documentation
**Other info**

update language codes and documentation

---

docs/development/example-store.json
docs/development/internationalization.md
td.vue/src/desktop/menu.js
td.vue/src/i18n/de.js
td.vue/src/i18n/el.js
td.vue/src/i18n/en.js
td.vue/src/i18n/es.js
td.vue/src/i18n/fr.js
td.vue/src/i18n/hi.js
td.vue/src/i18n/index.js
td.vue/src/i18n/ru.js
td.vue/src/i18n/uk.js
td.vue/src/i18n/zh.js
td.vue/src/store/modules/locale.js
td.vue/tests/unit/components/graph.spec.js
td.vue/tests/unit/components/localeSelect.spec.js

**Summary**
The language codes are now 3 character languages codes according to ISO 639-2
Also added Ukrainian along with the existing Russian
Three character lang codes to ISO 639-2
**Other info**

Three character lang codes to ISO 639-2

---

td.vue/src/i18n/es.js

**Summary**
Updates the translation file for Spanish
update spanish translation
**Other info**

Spanish Translations suggested, let me know any concerns

---

.github/workflows/release.yaml

**Summary**
This splits out installers within release pipeline, to aid debug and rerunning of failed pipeline stages
split out installers within release pipeline
**Other info**

update release pipeline

---

.github/workflows/ci.yaml
.github/workflows/housekeeping.yaml

**Summary**
updates Lychee and Trivy in the workflow actions
update workflow actions
**Other info**

update workflow actions

---

td.vue/src/components/Graph.vue
td.vue/src/components/ThreatEditDialog.vue
td.vue/src/store/modules/threatmodel.js
td.vue/tests/unit/components/graph.spec.js
td.vue/tests/unit/components/threatEditDialog.spec.js

**Summary**
This fixes the bug where the threat id number is incorrectly overwritten when editing the threat
fix bug for threat id number
**Other info**
closes #628

fix bug for threat id number

---

.github/workflows/ci.yaml
.github/workflows/release.yaml

**Summary**
adds a job to the release action and CI action that creates the SBOM
the github action 'sbom-action' detects of it is a release action and provides the SBOM as a release artifact
provide and publish sbom
**Other info**
closes #654

provide and publish sbom

---

.github/workflows/browserstack.yaml
.github/workflows/ci.yaml
.github/workflows/deploy.yaml
.github/workflows/housekeeping.yaml
.github/workflows/release.yaml

**Summary**
Adds action to the housekeeping workflow to remove any stale runs from workflows that are no longer used
Add action to remove runs from unused workflows
**Other info**
no issue for this, just a chore

Add action to remove runs from unused workflows

---

.github/workflows/ci.yaml
.github/workflows/deploy.yaml
.github/workflows/housekeeping.yaml
.github/workflows/release.yaml

**Summary**:
update versions of actions in pipelines
update versions of actions in pipelines

update actions in pipelines

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
.lycheeignore
.markdownlint.yaml
.release-note-template.md

**Summary**:
Apply a release note template to the release process
provide release note template

initial release note applied

---

td.vue/src/service/provider/providers.js
td.vue/src/store/modules/provider.js
td.vue/src/views/ReportModel.vue

**Summary**:
This provides alphanumeric sorting for the diagrams in the report, to allow some ordering in priority
sort diagrams alphanumerically in report
closes #696

sort diagrams alphanumerically in report

---

td.vue/src/i18n/de.js

Added German translation for #524. Wording for specific terms based on BSI (Bundesamt für Sicherheit in der Informationstechnik - Federal Office for Information Security) and on Githubs German website. 
closes #524

 I18N: add German translation #524

---

README.md
td.server/src/app.js

**Summary**:
* rename ci pipeline to push pipeline
pipeline updates

pipeline updates

---

.github/workflows/release.yaml
.release-note-template.md
package-lock.json
package.json
td.server/package-lock.json
td.server/package.json
td.vue/package-lock.json
td.vue/package.json
td.vue/src/store/modules/auth.js
td.vue/tests/e2e/specs/login.cy.js
td.vue/tests/e2e/specs/logout.cy.js
td.vue/tests/unit/store/modules/auth.spec.js

**Summary**:
rename versions to '2.0.5' and '-demo'
move to version 2.0.5

move to version 2.0.5

---

td.vue/package.json
td.vue/src/components/Graph.vue
td.vue/src/components/GraphMeta.vue
td.vue/src/components/GraphProperties.vue
td.vue/src/components/GraphThreats.vue
td.vue/src/service/x6/graph/graph.js
td.vue/src/views/ImportModel.vue
td.vue/tests/unit/components/graphMeta.spec.js
td.vue/tests/unit/components/graphThreats.spec.js
td.vue/tests/unit/service/x6/graph/graph.spec.js

**Summary**:
various improvements for diagrams prompted by some reported issues:
* restrict open file picker to just `.json` files
* clear away meta-data when the diagram is changed
* remove page boundaries from drawing canvas
various improvements for diagrams
closes #719 
closes #635

Various improvements for diagrams

---

td.vue/src/desktop/menu.js
td.vue/src/i18n/fi.js
td.vue/src/i18n/index.js
td.vue/tests/unit/desktop/menu.spec.js

This pull request contains an Initial Finnish language translation for the user interface.  
After translating the strings I checked how they work on the UI, and did some fine tuning. I did not translate STRIDE etc terms, because I don't think they should be translated. Working with them translated would be probably awkward.

Initial finnish translation.

---

.github/workflows/housekeeping.yaml
.github/workflows/pull_request.yaml
.github/workflows/push.yaml
.github/workflows/release.yaml
.release-note-template.md
release-process.md

**Summary**:
updates the workflow actions to the latest versions
update the workflow actions to the latest versions

update workflow actions to the latest

---

td.vue/src/components/GraphProperties.vue
td.vue/src/components/ThreatEditDialog.vue
td.vue/src/desktop/desktop.js
td.vue/src/service/x6/graph/data-changed.js
td.vue/src/service/x6/graph/events.js
td.vue/src/service/x6/shapes/flow.js
td.vue/tests/unit/service/x6/graph/data-changed.spec.js
td.vue/tests/unit/service/x6/graph/events.spec.js

**Summary**:
The component properties are not correctly updated at times - see bug #760 
component properties correctly updated
closes #760 

Component properties correctly updated

---

.github/workflows/browserstack.yaml
.github/workflows/housekeeping.yaml
.github/workflows/pull_request.yaml
.github/workflows/push.yaml
.github/workflows/release.yaml
td.server/package-lock.json
td.server/package.json
td.vue/package-lock.json
td.vue/package.json

**Summary**:
updates both workflow action versions and also package versions
update workflow action versions and package versions

update workflow action versions and package versions

---

td.vue/jest.config.js
td.vue/package-lock.json
td.vue/package.json

**Summary**:
This solves issue #790
Added node_modules axios to the ignorepath and rewrote the jest config file to force this change
I got the inspiration from this thread https://github.com/vercel/next.js/discussions/31152#discussioncomment-1697047
Closes #790

fix for #790

---

.github/workflows/pull_request.yaml
.github/workflows/push.yaml
release-process.md
td.vue/package.json
td.vue/src/components/Graph.vue
td.vue/src/store/modules/threatmodel.js
td.vue/src/views/HomePage.vue
td.vue/tests/unit/components/graphButtons.spec.js

**Summary**:
Adds a check to the use of config on the Home Page
Also adds instructions to create the checksums for the release installer images
add check for valid config on home page
Closes #808 
Closes #807

check for valid config on home page

---

td.vue/src/components/Graph.vue

**Summary**:
Solves #615 . The update lets the graph container resize every time the window size changes .
Changed the graph container css properties with a couple of more changes
Visual representation of how the update works : 
https://github.com/OWASP/threat-dragon/assets/94848646/7f13ceb6-29a3-4e09-9e82-f334aa7dfcd7

fixed graph container resizing issue

---

.github/workflows/housekeeping.yaml
.github/workflows/pull_request.yaml
.github/workflows/push.yaml
td.server/package-lock.json
td.server/package.json
td.vue/package-lock.json
td.vue/package.json
td.vue/src/components/LocaleSelect.vue

**Summary**:
updates github workflow actions:
* lycheeverse/lychee-action to version 1.9.0
* github/codeql-action/ to version 3.23.0
update github workflow actions

update github workflow actions

---

ThreatDragonModels/test-reports.json
td.vue/src/store/modules/threatmodel.js

**Summary**:
provides feedback that the model has been saved
add indication that model has been saved
closes #827

add indication that model has been saved

---

td.vue/src/service/x6/graph/events.js

**Summary**:
This PR enables multi-selection of components and resolves issue #844.

enable multi selection of components

---

.gitignore
ThreatDragonModels/test/example-open-threat-model.json
td.vue/src/assets/schema/open-threat-model-schema.js
td.vue/src/assets/schema/threat-model-schema.V2.js
td.vue/src/assets/schema/threat-model-schema.js
td.vue/src/components/Graph.vue
td.vue/src/components/GraphProperties.vue
td.vue/src/main.desktop.js
td.vue/src/service/ajv-SchemaVerification.js
td.vue/src/service/openThreatModel.js
td.vue/src/store/actions/threatmodel.js
td.vue/src/store/modules/threatmodel.js
td.vue/src/views/ImportModel.vue
td.vue/src/views/ThreatModelEdit.vue
td.vue/tests/unit/service/openThreatModel.spec.js

**Summary**:
Open Threat Model needs to be checked against a schema
add schema verification for OTM
closes #851

add schema verification for OTM

---

.gitignore
td.vue/public/preload.js
td.vue/src/components/Graph.vue
td.vue/src/desktop/desktop.js
td.vue/src/desktop/menu.js
td.vue/src/main.desktop.js
td.vue/src/store/modules/threatmodel.js
td.vue/tests/unit/desktop/menu.spec.js

**Summary**:
fixes unit tests for front end
fix unit tests for front end

fix unit tests for td.vue

---

td.vue/src/i18n/hi.js

**Summary**:
In the Hindi version of the page , the navbar appearance doesn't looks understandable for a Hindi user and also the [log out] hover appearance is written in English in place of Hindi
provide Hindi translation strings for hover text
Fixes: #862

Fixes:Navbar Issues

---

td.vue/src/i18n/hi.js

**Summary**:
We should get all the content in hindi
updates for hindi translation text
Fixes: #864

Fixes:td.vue/src/i8n/hi.js

---

td.vue/src/components/Navbar.vue

**Summary**:
Now Our Application Navbar will be looking Like below for Large screen width:
and for small screen width it will looks like :
provide visibility of logged in status for small screens
Fixes: #869

Fixes:Login Status Navbar

---

td.vue/src/desktop/desktop.js
td.vue/src/service/provider/providers.js
td.vue/src/service/schema/ajv.js

**Summary**:
the desktop auto updates without asking the user to agree, this could be irritating
prompt user before downloading desktop updates
closes #873

Desktop: prompt user before downloading auto updates

---

.github/workflows/housekeeping.yaml

**Summary**:
fix bug in housekeeping workflow
delete stale pull requests

delete stale pull requests

---

.github/workflows/housekeeping.yaml
.github/workflows/pull_request.yaml
.github/workflows/push.yaml

**Summary**:
fix up for permissions for various workflow actions
add permissions to workflows

add permissions to workflows

---

td.vue/src/desktop/menu.js
td.vue/src/i18n/id.js
td.vue/src/i18n/index.js
td.vue/tests/unit/desktop/menu.spec.js

**Summary**: Translated Vue I18n English language code to Bahasa Indonesia.
This pull request encompasses a comprehensive translation effort aimed at providing support for Bahasa Indonesia within the Vue I18n English language codebase. By leveraging the principles of internationalization and localization, the codebase has been extended to cater to Indonesian-speaking users, thereby enhancing the accessibility and usability of the application for a wider audience.
**Description for the changelog**: 
Translated to Bahasa Indonesia
- The translation process involved meticulous attention to detail to ensure the accuracy and fidelity of the Bahasa Indonesia equivalents to the original English strings. Every effort was made to maintain consistency and coherence throughout the …

Introducing Bahasa Indonesia Localization: Translation of Vue I18n English Language Code

---

.github/workflows/pull_request.yaml
.github/workflows/push.yaml
.github/workflows/release.yaml
td.server/package-lock.json
td.server/package.json
td.vue/package-lock.json
td.vue/package.json

**Summary**:
Collects together various updfates for workflow actions and npm package 'follow-redirects'
update versions for workflow actions

Update versions for workflow actions

---

.github/workflows/housekeeping.yaml
.github/workflows/pull_request.yaml
.github/workflows/push.yaml
.github/workflows/release.yaml
.trivyignore
Dockerfile
package-lock.json
package.json
td.vue/package-lock.json
td.vue/package.json
td.vue/wdio.config.js

**Summary**:
CI pipeline uses akhileshns/heroku-deploy
use heroku-deploy action in CI pipeline

Heroku-deploy action in CI pipeline

---

td.server/src/controllers/auth.js
td.server/src/controllers/threatmodelcontroller.js

**Summary**:
Fixes #999 
Complex objects properly stringified before given to the logger

fix: debug log displays objects properly

---

td.vue/package-lock.json
td.vue/package.json
td.vue/src/views/ThreatModelEdit.vue

**Summary**:
to increase usability when entering contributors, provide separators ';' and ',' along with enter key 
provide separator for contributor tags
closes #935 
closes pull request #1028

provide separator for contributor tags

---

.github/workflows/housekeeping.yaml
.github/workflows/pull_request.yaml
.github/workflows/push.yaml
.github/workflows/release.yaml

**Summary**:
update dependencies in workflows:
- github/codeql-action/
- docker/build-push-action
update dependencies in workflows

update dependencies in workflows

---

docs/Gemfile.lock
td.server/package-lock.json
td.server/package.json
td.vue/package-lock.json
td.vue/package.json

**Summary**:
Update frontend and server dependencies:
- docs rexml
- node-ipc
- ws
- webpack
- bootstrap (reverted)
- axios
- vue-template-compiler
update frontend and server dependencies

Update frontend and server dependencies

---

.github/workflows/housekeeping.yaml
.github/workflows/pull_request.yaml
.github/workflows/push.yaml
.github/workflows/release-snap.yaml
.github/workflows/release-windows.yaml
.github/workflows/release.yaml

**Summary**:
Update dependencies in workflow pipelines
update dependencies in workflow pipelines

update deps in workflow pipelines

---

td.vue/src/service/migration/diagram.js
td.vue/src/store/modules/threatmodel.js

**Summary**:
updates the threat model version in the file on save, to the version of the application
update model file version on save
closes #1142

Update model file version

---

td.vue/src/views/ThreatModel.vue

**Summary**:
provides both diagram description and icon in threat model view
both diagram description and icon in threat model view
closes #1168

Both diagram description and icon in threat model view

---

example.env
td.vue/package.json
td.vue/vue.config.js

**Summary**:
This pull request addresses issue #1158 and adds the ability for Threat Dragon to optionally support TLS if configured.
Adds the ability for Threat Dragon to optionally support TLS if configured
Closes #1158

add tls support issue #1158

---

td.vue/src/components/LocaleSelect.vue

**Summary**:
This PR solves issue #1193 by adding a search feature to the language selection dropdown. Instead of requiring users to scroll through list of languages, they can now search for a language using a text input field, improving user experience and accessibility.
- Added a search bar inside the language dropdown.
- Implemented filtering logic to prioritize exact and partial matches.
- Reset search query upon selection to enhance usability.
- Supported alternate language names for better search results.
https://github.com/user-attachments/assets/e43be332-645a-489e-b5e3-7f8aa82932cb

Added search functionality for language selection dropdown

---

td.vue/src/components/LocaleSelect.vue
td.vue/tests/unit/components/localeSelect.spec.js

**Summary**:
provides name in the navbar for the locale chosen
provides name in the navbar for the locale chosen

provide locale name in locale display

---

td.vue/src/store/modules/threatmodel.js

**Summary**:
This provides a toaster notification when the threat model is saved
provide confirmation that save has taken place
closes #1213

provide confirmation that save has taken place

---

.github/workflows/pull_request.yaml
.github/workflows/push.yaml
.github/workflows/release.yaml

**Summary**:
update workflows for latest versions of actions
update workflows for latest versions of actions
bundle of dependabot pull requests :
* #1210 
* #1216 
* #1217 
* #1218

update workflows for latest versions of actions

---

td.vue/src/service/x6/shapes/flow.js
td.vue/src/service/x6/shapes/trust-boundary-curve.js

**Summary**:
bug fix for data flow and trust boundary labels overwritten by curve
bug fix for data flow and trust boundary labels overwritten by curve
fixes #1231

Bug fix for data flows and trust boundary curve labels incorrectly displayed

---

.github/workflows/pull_request.yaml
.github/workflows/push.yaml
.github/workflows/release.yaml
docs/configure/bitbucket.md
docs/configure/github.md
docs/configure/gitlab.md
docs/configure/google.md

**Summary**:
update gitLab instructions so that they are consistent
also fixes a couple of pipeline dependencies
GitLab docs consistent
closes #1269

GitLab docs consistent

---

.github/workflows/housekeeping.yaml
.github/workflows/pull_request.yaml
.release-note-template.md
.wordlist.txt
README.md
docs/CNAME
docs/README.md
release-process.md

**Summary**:
Applies checks to docs when submitting a pull request :
- spell checker
- lint markdown
- link checker
Note that link checker is prone to failing due to too many requests
apply checks to docs on pull requests

apply checks to docs on pull requests

---

.github/workflows/housekeeping.yaml
.github/workflows/pull_request.yaml
.lycheeignore
td.vue/src/desktop/menu.js
td.vue/src/i18n/ar.js
td.vue/src/i18n/de.js
td.vue/src/i18n/el.js
td.vue/src/i18n/en.js
td.vue/src/i18n/es.js
td.vue/src/i18n/fi.js
td.vue/src/i18n/fr.js
td.vue/src/i18n/hi.js
td.vue/src/i18n/id.js
td.vue/src/i18n/ja.js
td.vue/src/i18n/ms.js
td.vue/src/i18n/pt.js
td.vue/src/i18n/ru.js
td.vue/src/i18n/uk.js
td.vue/src/i18n/zh.js
td.vue/tests/unit/desktop/menu.spec.js

**Summary**:
Adds the About Box for all platforms, not just MacOS
add about box for all platforms
- NA: functional tests created / modified for changes in functionality
closes #421

Add about box for all platforms

---

td.vue/src/components/printed-report/ExecutiveSummary.vue
td.vue/src/components/printed-report/ReportEntity.vue
td.vue/src/components/report/ExecutiveSummary.vue
td.vue/src/components/report/ReportEntity.vue
td.vue/src/i18n/ar.js
td.vue/src/i18n/de.js
td.vue/src/i18n/el.js
td.vue/src/i18n/en.js
td.vue/src/i18n/es.js
td.vue/src/i18n/fi.js
td.vue/src/i18n/fr.js
td.vue/src/i18n/hi.js
td.vue/src/i18n/id.js
td.vue/src/i18n/ja.js
td.vue/src/i18n/ms.js
td.vue/src/i18n/pt.js
td.vue/src/i18n/ru.js
td.vue/src/i18n/uk.js
td.vue/src/i18n/zh.js
td.vue/tests/e2e/specs/threatmodel/report.cy.js
td.vue/tests/unit/components/printed-report/executiveSummary.spec.js
td.vue/tests/unit/components/printed-report/reportEntity.spec.js
td.vue/tests/unit/components/report/executiveSummary.spec.js
td.vue/tests/unit/components/report/reportEntity.spec.js

**Summary**:
The Not Applicable threats were included in the Open threat totals - these need to be separate
also made sure that the Priority and Status was translated in the reports
separate Not Applicable threats from Open threats
closes #1265

Report: list Open and Not Applicable threats separately

---

docs/usage/diagrams.md
td.vue/src/components/GraphButtons.vue
td.vue/tests/unit/components/graphButtons.spec.js

**Summary**:
removed the JPEG export feature until the AntV/x6 library package is fixed
closes #1319 
remove JPEG export feature
raised an issue to reinstate the JPEG export feature #1323 once the AntV/x6 library is fixed

Remove JPEG export feature

---

.wordlist.txt
docs/development/translations.md
docs/home/about.md
td.vue/package-lock.json
td.vue/src/components/LocaleSelect.vue
td.vue/src/desktop/menu.js
td.vue/src/i18n/index.js
td.vue/src/i18n/ms.js
td.vue/tests/unit/desktop/menu.spec.js

**Summary**:
Changes Malay code to the 3 letter country code MSA, making it consistent with the other translations
Malay 3 letter country code
closes #1335

Malay 3 letter country code
